---
- name: Add gpg key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey

- name: Add nvidia-docker sources list
  get_url:
    url: https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list

- name: Install nvidia-docker
  apt:
    name: nvidia-docker2
    update_cache: yes 

- name: Reload Docker daemon configuration
  command: pkill -SIGHUP dockerd

- name: Run the nvidia-smi test
  command: docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
