---

- name: Download package
  get_url:
    url: "https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker-1.0.1-1.x86_64.rpm"
    dest: "/tmp/nvidia-docker.rpm"

- name: Install package
  yum: name=/tmp/nvidia-docker.rpm state=present
